### ISSUE TITLE
Love the project, but a little instruction on how to run would be amazing (⌒_⌒;)

### ISSUE THREAD

**Issue by DutchEllie** [ashuramaruzxc/anime-cursors#4]
I know nothing of Nix, but even after I got it running with some help from ChatGPT (is there some mixup between clickgen and cursorgen in pkgs/default.nix??) I just get `Unmatched files` errors when running:

```
[ellie@koumakan anime-cursors] :) $ ./src/__main__.py -p src/win/ルーミア　マウスカーソル/アニメーション/ -o Rumia --name Rumia --json src/config/definitions.json -vvv --format ani -r
Unmatched files: ルーミア　マウスカーソル　バックグラウンド作業中.ani, ルーミア　マウスカーソル　上下に拡大・縮小.ani, ルーミア　マウスカーソル　テキスト選択.ani, ルーミア　マウスカーソル　人の選択.ani, ルーミア　マウスカーソル　代替選択.ani, ルーミア　マウスカーソル　手書き.ani, ルーミア　マウスカーソル　待ち状態.ani, ルーミア　マウスカーソル　斜めに拡大・縮小2.ani, ルーミア　マウスカーソル　場所の選択.ani, ルーミア　マウスカーソル　移動.ani, ルーミア　マウスカーソル　ヘルプの選択.ani, ルーミア　マウスカーソル　左右に拡大・縮小.ani, ルーミア　マウスカーソル　通常.ani, ルーミア　マウスカーソル　利用不可.ani, ルーミア　マウスカーソル　領域選択.ani, ルーミア　マウスカーソル　リンク選択.ani, ルーミア　マウスカーソル　斜めに拡大・縮小1.ani
```

And I doubt that `./src/__main__.py` is how I'm supposed to run in the first place.

I love the project though! Especially the part where (I think?) you are also resizing the cursor images! That is awesome, and I don't think something anyone has done yet. 

---

Typed from my HDPI laptop running Wayland KDE with a tiny tiny Rumia cursor

**Comment by ashuramaruzxc** [comment]
> `Unmatched files` errors when running
means that there are probably something that doesn't matches in definitions_jp.json.
There are also a problem with some cursor theme because of 人の選択, i haven't decided yet how should i probably name it correctly to map to xcursors.

>And I doubt that ./src/__main__.py is how I'm supposed to run in the first place.
you should run pip and install my fork of win2xcur, or if you already have managed to setup nix just type 
`nix develop` or install direnv and run `direnv allow`
after that you can just type `python src/__main__.py arguments` here's an example:
`python src/__main__.py -p src/win/ルーミア　マウスカーソル/アニメーション --name Rumia --comment "something something`

**Comment by DutchEllie** [comment]
Oh thank you so much! I just pulled the most recent changes where you added the definition for 人の選択 and now I have it working!

You don't know how happy I am to finally have a consistently sized Rumia cursor ＼(＾▽＾)／
